# drm && docker-compose up


version: "2.7.8"

services:

  ##########################################
  #                 NGINX
  ##########################################
  nginx:
    image: nginx:latest
    container_name: mynginx
    depends_on :
      - php-fpm
    volumes:
      - ./html:/usr/share/nginx/html
      - ./default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - common_network
    ports:
      - '8001:80'
      
  ##########################################
  #                 PHP
  ##########################################
  php-fpm:
    build:
      context: .
    ## Mettre à jour le fichier 'default.conf'
    # -> fastcgi_pass myphp_fpm:9000;
    container_name: myphp_fpm
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydb
      POSTGRES_URL: mypostgres
      SMTP_URL: mymailpit
    volumes:
      - ./html:/usr/share/nginx/html
    networks:
      - common_network
    deploy:
      resources:
        limits:
          cpus: '0.5'
          # memory: 50M
        reservations:
          cpus: '0.3'
          # memory: 20M


  ##########################################
  #                POSTGRES
  ##########################################
  postgres:
    image: postgres:15.8-bookworm
    ## Mettre à jour le fichier 'phppgadmin/conf/config.inc.php'
    # apt update && apt-get install -y postgresql-client
    # PGPASSWORD='postgres' psql -h localhost -U postgres -d mydb
    # PGPASSWORD='postgres' psql -h mypostgres -U postgres -d mydb
    container_name: mypostgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydb
      PGDATA: /var/lib/postgresql/data

    volumes:
      - ./data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always
    networks:
      - common_network
    
    ## Accès de l'exterieur du 'container'
    ports:
      - "5432:5432"
    # shm_size: 128mb


  ##########################################
  #        VIRTUAL MAIL SERVER
  ##########################################
  mailpit:
    image: axllent/mailpit
    container_name: mymailpit
    networks:
      - common_network
    ports:
      - '1025:1025' # smtp://localhost:1025
      - '8025:8025' # http://localhost:8025
      
networks:
  common_network:
    name: common_network
    driver: bridge

